export const config = { maxDuration: 60 };
const SCHEMA = { type: 'OBJECT', properties: { title: { type: 'STRING' }, metaDescription: { type: 'STRING' }, content: { type: 'STRING' }, keyImprovementsIncluded: { type: 'ARRAY', items: { type: 'STRING' } }, faqSchemaJson: { type: 'STRING' } }, required: ['title','metaDescription','content','keyImprovementsIncluded'] };
export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*'); res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS'); res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  if (req.method === 'OPTIONS') return res.status(200).end(); if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });
  const key = process.env.GEMINI_API_KEY || ''; const i = req.body || {}; if (!key) return res.status(500).json({ error: 'Proxy is missing GEMINI_API_KEY' }); if (!i.seoData && !i.recommendations) return res.status(400).json({ error: 'SEO data or recommendations required.' });
  const length = i.targetLength === 'comprehensive' ? '2,000+ words' : i.targetLength === 'concise' ? '800-1,200 words' : '1,400-2,000 words';
  const prompt = `Write the COMPLETE publication-ready refreshed travel article in Markdown, not an outline.\nTone: ${i.tone || 'Authoritative Local Guide'}\nLength: ${length}\nCustom instructions: ${i.customPrompt || 'Apply every audit finding.'}\nPage data: ${JSON.stringify({ ...(i.seoData || {}), mainContent: (i.seoData?.mainContent || '').slice(0, 9000) })}\nAudit: ${JSON.stringify(i.recommendations || {})}\nUse an optimized H1, strong introduction, useful H2/H3 sections, named entities, practical local tips, internal-link suggestions, FAQs${i.includeCta === false ? '' : ', and useful conversion CTAs'}. ${i.includeFaqSchema === false ? 'Leave faqSchemaJson empty.' : 'Include valid FAQPage JSON-LD in faqSchemaJson.'}`;
  try { const r = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-3.6-flash:generateContent?key=${encodeURIComponent(key)}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, signal: AbortSignal.timeout(50000), body: JSON.stringify({ contents: [{ role: 'user', parts: [{ text: prompt }] }], generationConfig: { temperature: 0.4, responseMimeType: 'application/json', responseSchema: SCHEMA } }) }); const data = await r.json(); if (!r.ok) return res.status(r.status === 429 ? 429 : 502).json({ error: data?.error?.message || `Gemini HTTP ${r.status}` }); const text = (data?.candidates?.[0]?.content?.parts || []).map((p) => p.text || '').join(''); const parsed = JSON.parse(text); const words = (parsed.content || '').split(/\s+/).filter(Boolean).length; return res.status(200).json({ success: true, article: { ...parsed, wordCount: words, readingTimeMinutes: Math.max(1, Math.ceil(words / 200)), generatedAt: new Date().toISOString() } }); }
  catch (error) { return res.status(error?.name === 'TimeoutError' ? 504 : 500).json({ error: error?.message || 'Article generation failed' }); }
}
